### PR TITLE
Add vscode html-data for teddy tags.

### PR DESCRIPTION
**Pull request by hudson-pace**
Creates an html-data.json file defining the different tags, and adds it to vscode settings. Addresses #322

### CODE REVIEW

**Comment by kethinov** [comment]
@lannonbr can you take a look at this, since you are our resident VS Code expert?

**Comment by lannonbr** [comment]
So I did some digging and it seems that we can't generate a `.vscode/settings.json` file in the Teddy package and have those settings propogate up, but rather the `.vscode` folder would be the workspace settings if you were working on Teddy itself.

That said, if you copy that text into a project which is using teddy it can work. So for instance, here's an example `settings.json` file I made in a new project where I'm including teddy:

```json
{
  "html.customData": [
    "./node_modules/teddy/.vscode/teddyTags.html-data.json"
  ]
}
```

And then if I'm writing a template the metadata will start appearing:

Screenshot 2021-03-10 194642

**Comment by lannonbr** [comment]
As well, the `teddyTags.html-data.json` file should be added to the `files` field in the package.json so it will be shipped with the package on a publish.

**Comment by kethinov** [comment]
Is there any point to publishing this with the package if it doesn't propagate to end users consuming the package via npm?

**Comment by lannonbr** [comment]
So another solution from what I'm seeing in the docs is adding it as part of an extension, so we could possibly update [vscode-teddy](https://github.com/lannonbr/vscode-teddy) to include this.

**Comment by kethinov** [comment]
Good idea. Give that a shot @hudson-pace?

**Pull request closed without merging**
